version: '3'

services:
  tomcat:
    container_name: tomcat-composed
    restart: always
    image: tomcat:latest
    ports:
    - 80:8080
    volumes:
    - /home/regev/Desktop/Final:/usr/local/tomcat/webapps/Final
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  jenkins:
        container_name: jenkins-composed
        restart: always
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8080:8080
            - 50000:50000
        
        volumes:
            - /home/regev/Desktop/Final/jenkins_configuration:/var/jenkins_home
        stdin_open: true # docker run -i
        tty: true        # docker run -t
